// ============================================
// SOBEI Portal — Mock Data
// ============================================

export const UNIDADES = [
  'Acácias',
  'Araucárias',
  'Bela Vista',
  'CCINTER',
  'CEDESP',
  'Cedro',
  'Cerejeiras/Jacomo Tatto',
  'Imbuias',
  'Ipês',
  'Leblon',
  'Macaúbas',
  'Matriz',
  'Montanaro',
  'NCI Imbuias',
  'Oliveiras',
  'Orquídeas',
  'Sabiás',
  'Telecentro'
];

export const MOCK_DENUNCIAS = [
  {
    id: '1',
    protocolo: 'DXH-957-437',
    tipo: 'anonima',
    unidade: 'Leblon',
    descricao:
      'Gostaria de relatar uma inconsistência grave que vem ocorrendo de forma recorrente nas últimas três semanas. O supervisor Carlos Eduardo tem dado baixa no sistema acusando o recebimento de lotes completos de caixas de papelão da empresa LogPack. No entanto, fisicamente, apenas metade da carga descrita na nota fiscal está entrando no galpão.\nNa última terça-feira (26/05), presenciei o momento em que o caminhão descarregou 50 pallets, mas a nota fiscal assinada e validada por ele constava o recebimento de 100 pallets. Suspeito de um esquema fraudulento de faturamento duplicado entre o supervisor e o fornecedor externo, gerando prejuízo financeiro direto para a nossa unidade. Os relatórios de inventário do sistema não vão bater com o estoque físico se uma auditoria for realizada de surpresa.',
    envolvidos: 'Mariana Alencar (Coordenadora de Atendimento)\nMariana 2 (Coordenadora de algo)',
    testemunhas: 'Maria testemunha',
    dataEnvio: '18/06/2025',
    status: 'na_fila',
    nome: null,
    email: null,
    telefone: null,
    dataAbertura: null,
    ultimaAlteracao: null,
    dataFechamento: null,
    dataArquivamento: null,
    medidasAdotadas: '',
    relatorioFinal: '',
    relatorioArquivamento: '',
    categoria: '',
  },
  {
    id: '2',
    protocolo: 'THC-420-759',
    tipo: 'identificada',
    unidade: 'Leblon',
    descricao:
      'Relato de assédio moral constante por parte do gerente da unidade. O mesmo faz comentários depreciativos em público sobre funcionários, ameaça demissão sem justa causa e cria ambiente de trabalho hostil. Diversos colegas já presenciaram mas têm medo de denunciar.',
    envolvidos: 'Roberto Silva (Gerente de Unidade)',
    testemunhas: 'João Pedro, Ana Clara',
    dataEnvio: '15/06/2025',
    status: 'em_andamento',
    nome: 'Carlos Henrique',
    email: 'carlos.h@email.com',
    telefone: '(11) 98765-4321',
    dataAbertura: '19/06/2025',
    ultimaAlteracao: '20/06/2025',
    dataFechamento: null,
    dataArquivamento: null,
    medidasAdotadas: '',
    relatorioFinal: '',
    relatorioArquivamento: '',
    categoria: 'Assédio moral',
  },
  {
    id: '3',
    protocolo: 'RBX-112-845',
    tipo: 'anonima',
    unidade: 'Montanaro',
    descricao:
      'Funcionários estão utilizando veículos da empresa para fins pessoais nos finais de semana. Já vi pelo menos 3 ocasiões em que o carro da frota estava estacionado em shopping centers durante o sábado.',
    envolvidos: 'Equipe de logística',
    testemunhas: 'Não informado',
    dataEnvio: '10/06/2025',
    status: 'em_andamento',
    nome: null,
    email: null,
    telefone: null,
    dataAbertura: '19/06/2025',
    ultimaAlteracao: '20/06/2025',
    dataFechamento: null,
    dataArquivamento: null,
    medidasAdotadas: '',
    relatorioFinal: '',
    relatorioArquivamento: '',
    categoria: 'Uso indevido de recursos',
  },
  {
    id: '4',
    protocolo: 'KLM-334-912',
    tipo: 'identificada',
    unidade: 'Ipês',
    descricao:
      'Percebi irregularidades na contabilidade da unidade. Valores de caixa não conferem com os registros do sistema há pelo menos dois meses. A diferença acumulada já ultrapassa R$ 15.000,00.',
    envolvidos: 'Fernando Costa (Analista Financeiro)',
    testemunhas: 'Patrícia Mendes',
    dataEnvio: '05/06/2025',
    status: 'fechada',
    nome: 'Luciana Ferreira',
    email: 'lu.ferreira@email.com',
    telefone: '(11) 91234-5678',
    dataAbertura: '19/06/2025',
    ultimaAlteracao: '20/06/2025',
    dataFechamento: '24/06/2025',
    dataArquivamento: null,
    medidasAdotadas:
      'A denuncia foi apurada, o supervisor Carlos Eduardo já está afastado no momento e passará por um curso de reciclagem.',
    relatorioFinal:
      'A denuncia foi apurada, o supervisor Carlos Eduardo já está afastado no momento e passará por um curso de reciclagem.',
    relatorioArquivamento: '',
    categoria: 'Fraude financeira',
  },
  {
    id: '5',
    protocolo: 'WQP-667-210',
    tipo: 'anonima',
    unidade: 'Bela Vista',
    descricao:
      'Denúncia sobre condições insalubres no refeitório. Alimentos sendo armazenados de forma incorreta, sem refrigeração adequada. Já houve casos de intoxicação alimentar entre os funcionários.',
    envolvidos: 'Empresa terceirizada de alimentação',
    testemunhas: 'Diversos funcionários',
    dataEnvio: '01/06/2025',
    status: 'fechada',
    nome: null,
    email: null,
    telefone: null,
    dataAbertura: '19/06/2025',
    ultimaAlteracao: '20/06/2025',
    dataFechamento: '24/06/2025',
    dataArquivamento: null,
    medidasAdotadas:
      'Visita sanitária realizada. Empresa terceirizada notificada oficialmente.',
    relatorioFinal:
      'Após inspeção, foram encontradas irregularidades confirmando a denúncia. A empresa foi multada e um novo contrato será licitado.',
    relatorioArquivamento: '',
    categoria: 'Saúde e segurança',
  },
  {
    id: '6',
    protocolo: 'JNH-889-553',
    tipo: 'anonima',
    unidade: 'Leblon',
    descricao:
      'Denúncia duplicada sobre o mesmo assunto da DXH-957-437. Sem informações adicionais relevantes.',
    envolvidos: 'Não informado',
    testemunhas: 'Não informado',
    dataEnvio: '20/06/2025',
    status: 'arquivada',
    nome: null,
    email: null,
    telefone: null,
    dataAbertura: '19/06/2025',
    ultimaAlteracao: '20/06/2025',
    dataFechamento: null,
    dataArquivamento: '24/06/2025',
    medidasAdotadas:
      'A denuncia foi apurada, o supervisor Carlos Eduardo já está afastado no momento e passará por um curso de reciclagem.',
    relatorioFinal: '',
    relatorioArquivamento:
      'A denuncia foi apurada, o supervisor Carlos Eduardo já está afastado no momento e passará por um curso de reciclagem.',
    categoria: 'Duplicada',
  },
  {
    id: '7',
    protocolo: 'VBN-441-876',
    tipo: 'identificada',
    unidade: 'Araucarias',
    descricao:
      'Relato de favorecimento em processo seletivo interno. Candidata com menos qualificação foi promovida em detrimento de outros com mais experiência, aparentemente por relação pessoal com o gestor.',
    envolvidos: 'Marcos Oliveira (Gestor de RH)',
    testemunhas: 'Equipe do setor administrativo',
    dataEnvio: '12/06/2025',
    status: 'na_fila',
    nome: 'Juliana Santos',
    email: 'ju.santos@email.com',
    telefone: '(11) 99876-5432',
    dataAbertura: null,
    ultimaAlteracao: null,
    dataFechamento: null,
    dataArquivamento: null,
    medidasAdotadas: '',
    relatorioFinal: '',
    relatorioArquivamento: '',
    categoria: '',
  },
  {
    id: '8',
    protocolo: 'ZXC-553-198',
    tipo: 'anonima',
    unidade: 'Ipês',
    descricao:
      'Presenciei manipulação de ponto eletrônico. Funcionário registra entrada no horário correto mas sai mais cedo, com outro colega registrando sua saída no horário oficial.',
    envolvidos: 'Não identificados por segurança',
    testemunhas: 'Prefiro não informar',
    dataEnvio: '22/06/2025',
    status: 'na_fila',
    nome: null,
    email: null,
    telefone: null,
    dataAbertura: null,
    ultimaAlteracao: null,
    dataFechamento: null,
    dataArquivamento: null,
    medidasAdotadas: '',
    relatorioFinal: '',
    relatorioArquivamento: '',
    categoria: '',
  },
  {
    id: '9',
    protocolo: 'MNB-776-321',
    tipo: 'anonima',
    unidade: 'Araucarias',
    descricao:
      'Desvio de materiais de escritório em grande quantidade. Resmas de papel, cartuchos de tinta e outros suprimentos somem do estoque sem requisição formal.',
    envolvidos: 'Setor de almoxarifado',
    testemunhas: 'Funcionários do andar',
    dataEnvio: '08/06/2025',
    status: 'arquivada',
    nome: null,
    email: null,
    telefone: null,
    dataAbertura: '19/06/2025',
    ultimaAlteracao: '20/06/2025',
    dataFechamento: null,
    dataArquivamento: '24/06/2025',
    medidasAdotadas: 'Investigação inicial não encontrou evidências suficientes.',
    relatorioFinal: '',
    relatorioArquivamento:
      'Após análise preliminar, não foram encontradas evidências que sustentem a denúncia. Caso arquivado por falta de provas.',
    categoria: 'Insuficiência de provas',
  },
  {
    id: '10',
    protocolo: 'QWE-998-654',
    tipo: 'identificada',
    unidade: 'Leblon',
    descricao:
      'Denúncia sobre descumprimento de normas de segurança do trabalho. EPIs não estão sendo fornecidos adequadamente e máquinas operam sem manutenção preventiva.',
    envolvidos: 'Coordenação de segurança do trabalho',
    testemunhas: 'Técnicos de manutenção',
    dataEnvio: '18/06/2025',
    status: 'em_andamento',
    nome: 'Ricardo Almeida',
    email: 'ricardo.a@email.com',
    telefone: '(11) 97654-3210',
    dataAbertura: '19/06/2025',
    ultimaAlteracao: '20/06/2025',
    dataFechamento: null,
    dataArquivamento: null,
    medidasAdotadas: '',
    relatorioFinal: '',
    relatorioArquivamento: '',
    categoria: 'Segurança do trabalho',
  },
];

// Estatísticas mock por unidade
export const MOCK_STATS_POR_UNIDADE = [
  { unidade: 'Leblon', total: 100 },
  { unidade: 'Montanaro', total: 72 },
  { unidade: 'Ipês', total: 95 },
  { unidade: 'Bela Vista', total: 22 },
  { unidade: 'Araucarias', total: 45 },
  { unidade: 'Matriz', total: 60 },
];

export const MOCK_STATS_DISTRIBUICAO = [
  { unidade: 'Ipês', percentual: 35.0, cor: '#7C6BC4' },
  { unidade: 'Araucarias', percentual: 25.0, cor: '#9C8FD9' },
  { unidade: 'Bela Vista', percentual: 20.0, cor: '#FFB74D' },
  { unidade: 'Leblon', percentual: 10.0, cor: '#43A047' },
  { unidade: 'Montanaro', percentual: 10.0, cor: '#FF7043' },
];
